### PR TITLE
R: Fixed unable to find rpc/types.h when building from source on Ubuntu 20.10

### LINKED ISSUE #21759: Building R from source on Ubuntu in WSL 2 fails
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install R from source in Ubuntu 20.10 running on WSL 2. The output of `brew gist-logs r` [can be found here](https://gist.github.com/eced8272c083a7e6bff48bd1ea602b8d).

Note that I couldn't quite fix all `brew doctor` issues as `gcc` depends on `isl@0.18`, which is deprecated.

## What happened (include command output)

The build failed with the message that `rpc/types.h` could not be found.

<details>
  <summary>Command output</summary>
  <pre>

  ==> Downloading https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz
Already downloaded: /home/vsong/.cache/Homebrew/downloads/d0aba331f24b5d794d1b83d73e826f2ddaeb191efa58fd088d80eaba45d7450b--R-4.0.3.tar.gz
==> Reinstalling r
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/r/4.0.3 --enable-memory-profiling --with-lapack --enable-R-shlib --disable-java --with-blas=-L/home/linuxbrew/.linuxbrew/opt/openblas/lib -lopenblas SED=/usr/bin/sed --libdir=/home/linuxbrew/.
==> make
Last 15 lines from /home/vsong/.cache/Homebrew/Logs/r/02.make:
gcc-5 -I../../src/extra -I/usr/include/tirpc -I. -I../../src/include -I../../src/include -I/home/linuxbrew/.linuxbrew/Cellar/curl/7.74.0/include -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/readline/include -I../../src/nmath -DHAVE_CONFIG_H   -fopenmp -fpic  -g -O2  -c serialize.c -o serialize.o
gcc-5 -I../../src/extra -I/usr/include/tirpc -I. -I../../src/include -I../../src/include -I/home/linuxbrew/.linuxbrew/Cellar/curl/7.74.0/include -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/readline/include -I../../src/nmath -DHAVE_CONFIG_H   -fopenmp -fpic  -g -O2  -c sort.c -o sort.o
saveload.c:115:23: fatal error: rpc/types.h: No such file or directory
compilation terminated.
make[3]: *** [../../Makeconf:125: saveload.o] Error 1
make[3]: *** Waiting for unfinished jobs....
serialize.c:885:23: fatal error: rpc/types.h: No such file or directory
compilation terminated.
make[3]: *** [../../Makeconf:125: serialize.o] Error 1
make[3]: Leaving directory '/tmp/r-20201210-10532-1h907y5/R-4.0.3/src/main'
make[2]: *** [Makefile:138: R] Error 2
make[2]: Leaving directory '/tmp/r-20201210-10532-1h907y5/R-4.0.3/src/main'
make[1]: *** [Makefile:28: R] Error 1
make[1]: Leaving directory '/tmp/r-20201210-10532-1h907y5/R-4.0.3/src'
make: *** [Makefile:61: R] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

The build should have succeeded.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install -s r`

### PR DESCRIPTION
**Pull request by Tyrubias**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [x] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----
This fixes #21759. Logs can be [found here](https://gist.github.com/756b19383c194f4bc25569b00d3fdef2).

### CODE REVIEW

**Comment by Tyrubias** [comment]
Should I delete the `linux` section in the `bottles do ... end` section?

**Comment by gromgit** [comment]
> Should I delete the `linux` section in the `bottles do ... end` section?

No, the `bottles` section is managed by CI.

**Comment by Tyrubias** [comment]
@gromgit Any idea what I should do to fix the CI errors?

**Comment by gromgit** [comment]
I'm stumped. @Homebrew/linux , any idea what's going on here?

File: Formula/r.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ class R < Formula
   url "https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz"
   sha256 "09983a8a78d5fb6bc45d27b1c55f9ba5265f78fa54a55c13ae691f87c5bb9e0d"
   license "GPL-2.0-or-later"
-  revision 1
```
Comment (iMichka) [inline Formula/r.rb:7]: revision OS.mac? ? 1 : 2

**Comment by iMichka** [comment]
You need to delete the ` sha256 "0429f284050a1f1fde4c962cca7fde184b7334cb21fddde287eb38bb16d2c9c8" => :x86_64_linux` line here as you are bumping the revision.

The linux CI setup is not that clever. We are using --keep-old here. This won't be necessary when we move everything to homebrew-core.

File: Formula/r.rb (hunk 1 above)
Comment (gromgit) [reply Formula/r.rb:7]: @iMichka, for future reference, do revision numbers have to be sequential, or just need to be monotonically increasing?

**Comment by iMichka** [comment]
Thanks @Tyrubias !

File: Formula/r.rb (hunk 1 above)
Comment (iMichka) [reply Formula/r.rb:7]: In linuxbrew-core, we do not touch the Mac revision number. So the revision might be bumped and diverge from the Mac one. This is something we will need to discuss for homebrew-core once we start bottling for Linux. Because the dependency tree is different on Linux, an update in there might trigger a unnecessary rev-bump for a Mac formula. And this is probably not what we want.
